# Generated by Django 4.2.1 on 2023-08-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0029_following_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='slug',
            field=models.SlugField(default='temp', unique=True),
        ),
    ]
